language: ruby
rvm:
  - 2.6.4
before_install:
  - gem update --system
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install v12
  - node -v
  - npm i -g yarn
  - yarn
services:
  - postgresql

before_script:
  - "psql -c 'create database travis_ci_test;' -U postgres"
  - "bundle exec rake db:migrate"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rails test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
