name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0     

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: Install yarn
        run: |
          npm install --global yarn
      
      - name: Add webpacker before yarn install # solves node-sass error
        run: |
          yarn add @rails/webpacker
      
      # - name: yarn install --check-files # --check-files ensures @rails/webpacker dependencies aren't overwritten
      #   run: |
      #     sudo yarn install --check-files
      
      - name: Compile Webpacker
        run: bundle exec rails webpacker:compile
        env:
          RAILS_ENV: test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: rails test
          debug: true      
